### ISSUE TITLE
ASP.NET Core code

### ISSUE THREAD

**Issue by HamidBaghernia** [ImanX/zarinpal-dotNet#8]
Hi there,
Thanks for the code.

Is it possible to upgrade your code to ASP.NET MVC or ASP.NET Core MVC?
The web form technology is not supported by Microsoft any more.

Thank you.

**Comment by ImanX** [comment]
@Hamidnwo 
Hi
This repo is free for PL
if you want that change and develop it, you can do it.
we'll support and merging it.
